export type ToolPhase = 1 | 2 | 3 | 4;
export type ProcessingMode = "local" | "hybrid" | "cloud";

export type ToolCategoryId =
  | "edit-compress"
  | "split-merge"
  | "from-pdf"
  | "to-pdf"
  | "sign-security"
  | "audio-video";

export interface ToolDefinition {
  slug: string;
  name: string;
  description: string;
  category: ToolCategoryId;
  phase: ToolPhase;
  mode: ProcessingMode;
  available: boolean;
  accent: string;
}

export interface ToolCategory {
  id: ToolCategoryId;
  title: string;
  accent: string;
}

export const categories: ToolCategory[] = [
  { id: "edit-compress", title: "Edit & Sign", accent: "#f472b6" },
  { id: "split-merge", title: "Organize Pages", accent: "#fb7185" },
  { id: "from-pdf", title: "Convert from PDF", accent: "#60a5fa" },
  { id: "to-pdf", title: "Convert to PDF", accent: "#fb923c" },
  { id: "sign-security", title: "Secure & Extra", accent: "#2dd4bf" },
  { id: "audio-video", title: "Audio & Video", accent: "#a78bfa" },
];

export const tools: ToolDefinition[] = [
  // Phase 1 — available
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Shrink PDF size with a local light pass; heavy compress via cloud later.",
    category: "edit-compress",
    phase: 1,
    mode: "hybrid",
    available: true,
    accent: "#f472b6",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one file, fully offline.",
    category: "split-merge",
    phase: 1,
    mode: "local",
    available: true,
    accent: "#fb7185",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Click between pages to add colored splits, or extract selected pages.",
    category: "split-merge",
    phase: 2,
    mode: "local",
    available: true,
    accent: "#fb7185",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    description: "Render each PDF page to a PNG image.",
    category: "from-pdf",
    phase: 1,
    mode: "local",
    available: true,
    accent: "#60a5fa",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Render each PDF page to a JPG image.",
    category: "from-pdf",
    phase: 1,
    mode: "local",
    available: true,
    accent: "#60a5fa",
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    description: "Build a PDF from PNG or JPG images.",
    category: "to-pdf",
    phase: 1,
    mode: "local",
    available: true,
    accent: "#fb923c",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection when you know the password.",
    category: "sign-security",
    phase: 1,
    mode: "local",
    available: true,
    accent: "#2dd4bf",
  },

  // Later phases — catalog only (Forms excluded)
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Edit the actual PDF text runs locally — same size/color, no cover overlay.",
    category: "edit-compress",
    phase: 4,
    mode: "local",
    available: true,
    accent: "#f472b6",
  },
  {
    slug: "annotate-pdf",
    name: "Annotate PDF",
    description: "Highlight, draw, sticky notes, and markup tools.",
    category: "edit-compress",
    phase: 3,
    mode: "local",
    available: true,
    accent: "#f472b6",
  },
  {
    slug: "organize-pdf",
    name: "Organize PDF",
    description: "Drag page thumbnails to reorder pages inside one PDF.",
    category: "split-merge",
    phase: 2,
    mode: "local",
    available: true,
    accent: "#fb7185",
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    description: "Select pages to extract into one PDF or separate files.",
    category: "split-merge",
    phase: 2,
    mode: "local",
    available: true,
    accent: "#fb7185",
  },
  {
    slug: "delete-pages",
    name: "Delete Pages",
    description: "Remove pages from a PDF via thumbnail controls.",
    category: "split-merge",
    phase: 2,
    mode: "local",
    available: true,
    accent: "#fb7185",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate pages 90° clockwise or counterclockwise.",
    category: "split-merge",
    phase: 2,
    mode: "local",
    available: true,
    accent: "#fb7185",
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Crop the current page or all pages.",
    category: "edit-compress",
    phase: 2,
    mode: "local",
    available: false,
    accent: "#f472b6",
  },
  {
    slug: "create-pdf",
    name: "Create PDF",
    description: "Start a blank PDF document.",
    category: "edit-compress",
    phase: 2,
    mode: "local",
    available: false,
    accent: "#f472b6",
  },
  {
    slug: "translate-pdf",
    name: "Translate PDF",
    description: "Local translation (coming later).",
    category: "edit-compress",
    phase: 4,
    mode: "local",
    available: false,
    accent: "#f472b6",
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    description: "Local OCR to searchable PDF or plain text (Tesseract).",
    category: "edit-compress",
    phase: 4,
    mode: "local",
    available: true,
    accent: "#f472b6",
  },
  {
    slug: "fill-pdf",
    name: "Fill PDF",
    description: "Fill interactive PDF form fields.",
    category: "edit-compress",
    phase: 3,
    mode: "local",
    available: true,
    accent: "#f472b6",
  },
  {
    slug: "compress-images",
    name: "Compress Images",
    description: "Reduce image file sizes.",
    category: "edit-compress",
    phase: 2,
    mode: "local",
    available: false,
    accent: "#f472b6",
  },
  {
    slug: "enhance-image",
    name: "Enhance Image",
    description: "Improve image clarity and quality.",
    category: "edit-compress",
    phase: 3,
    mode: "hybrid",
    available: false,
    accent: "#f472b6",
  },
  {
    slug: "merge-images",
    name: "Merge Images",
    description: "Combine images into one document or collage.",
    category: "split-merge",
    phase: 2,
    mode: "local",
    available: false,
    accent: "#fb7185",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF to editable DOCX.",
    category: "from-pdf",
    phase: 3,
    mode: "cloud",
    available: false,
    accent: "#60a5fa",
  },
  {
    slug: "pdf-to-epub",
    name: "PDF to EPUB",
    description: "Convert PDF to EPUB ebook format.",
    category: "from-pdf",
    phase: 4,
    mode: "cloud",
    available: false,
    accent: "#60a5fa",
  },
  {
    slug: "pdf-to-pptx",
    name: "PDF to PPTX",
    description: "Convert PDF pages into a PowerPoint deck.",
    category: "from-pdf",
    phase: 3,
    mode: "cloud",
    available: false,
    accent: "#60a5fa",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables into Excel spreadsheets.",
    category: "from-pdf",
    phase: 3,
    mode: "cloud",
    available: false,
    accent: "#60a5fa",
  },
  {
    slug: "pdf-to-html",
    name: "PDF to HTML",
    description: "Convert PDF content to HTML.",
    category: "from-pdf",
    phase: 3,
    mode: "hybrid",
    available: false,
    accent: "#60a5fa",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert DOCX documents to PDF.",
    category: "to-pdf",
    phase: 3,
    mode: "cloud",
    available: false,
    accent: "#fb923c",
  },
  {
    slug: "epub-to-pdf",
    name: "EPUB to PDF",
    description: "Convert EPUB books to PDF.",
    category: "to-pdf",
    phase: 4,
    mode: "cloud",
    available: false,
    accent: "#fb923c",
  },
  {
    slug: "pptx-to-pdf",
    name: "PPTX to PDF",
    description: "Convert PowerPoint decks to PDF.",
    category: "to-pdf",
    phase: 3,
    mode: "cloud",
    available: false,
    accent: "#fb923c",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert spreadsheets to PDF.",
    category: "to-pdf",
    phase: 3,
    mode: "cloud",
    available: false,
    accent: "#fb923c",
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Render HTML pages to PDF.",
    category: "to-pdf",
    phase: 2,
    mode: "local",
    available: false,
    accent: "#fb923c",
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Draw, type, or upload a signature and place it on the page.",
    category: "sign-security",
    phase: 3,
    mode: "local",
    available: true,
    accent: "#2dd4bf",
  },
  {
    slug: "protect-pdf",
    name: "Password Protect PDF",
    description: "Add open/permission passwords to a PDF.",
    category: "sign-security",
    phase: 3,
    mode: "local",
    available: true,
    accent: "#2dd4bf",
  },
  {
    slug: "remove-watermark",
    name: "Remove Watermark",
    description: "Clean watermarks from PDFs where possible.",
    category: "sign-security",
    phase: 4,
    mode: "hybrid",
    available: false,
    accent: "#2dd4bf",
  },
  {
    slug: "generate-qr",
    name: "Generate QR Code",
    description: "Create QR codes for links and text.",
    category: "sign-security",
    phase: 2,
    mode: "local",
    available: false,
    accent: "#2dd4bf",
  },
  {
    slug: "pdf-summarizer",
    name: "PDF Summarizer",
    description: "AI summary of long PDF documents.",
    category: "edit-compress",
    phase: 4,
    mode: "cloud",
    available: false,
    accent: "#f472b6",
  },
  {
    slug: "media-convert",
    name: "Media Conversion",
    description: "Convert between audio and video formats.",
    category: "audio-video",
    phase: 4,
    mode: "hybrid",
    available: false,
    accent: "#a78bfa",
  },
  {
    slug: "video-compress",
    name: "Video Compression",
    description: "Reduce video file size.",
    category: "audio-video",
    phase: 4,
    mode: "hybrid",
    available: false,
    accent: "#a78bfa",
  },
  {
    slug: "transcription",
    name: "Transcription",
    description: "Transcribe audio, video, or YouTube links.",
    category: "audio-video",
    phase: 4,
    mode: "cloud",
    available: false,
    accent: "#a78bfa",
  },
  {
    slug: "ai-audio",
    name: "AI Audio Tools",
    description: "Vocal remover, TTS, and music generation.",
    category: "audio-video",
    phase: 4,
    mode: "cloud",
    available: false,
    accent: "#a78bfa",
  },
];

export function getTool(slug: string): ToolDefinition | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function toolsByCategory(categoryId: ToolCategoryId): ToolDefinition[] {
  return tools.filter((tool) => tool.category === categoryId);
}
